server:
  port: 8082

spring:
  application:
    name: queryservice
  datasource:
    url: jdbc:postgresql://localhost:5432/trail_races
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "eW91ci0yNTYtYml0LXNlY3JldC15b3VyLTI1Ni1iaXQtc2VjcmV0"
  expiration: 86400000
