server:
  port: 8081

spring:
  application:
    name: commandservice
  datasource:
    url: jdbc:postgresql://localhost:5432/trail_races
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

jwt:
  secret: "eW91ci0yNTYtYml0LXNlY3JldC15b3VyLTI1Ni1iaXQtc2VjcmV0"
  expiration: 86400000
